"""
Django settings for mozlando project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import datetime
import os

from decouple import config


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'il0+rg-q7_b6z00r5j33#(x*r!87j*4r+761rh0^!@_p8794+^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'mozlando.untappd'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mozlando.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mozlando.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Parse database configuration from $DATABASE_URL
import dj_database_url
DATABASES['default'] =  dj_database_url.config()

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow all host headers
ALLOWED_HOSTS = ['*']

# Static asset configuration
import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
)

SITE_ID = 1

ACCOUNT_DEFAULT_HTTP_PROTOCOL = config('ACCOUNT_DEFAULT_HTTP_PROTOCOL', 'http')

DEFAULT_CACHE_AGE = int(os.getenv('DEFAULT_CACHE_AGE', 60 * 60 * 24 * 7))
CACHE_PATH_TMPL = 'cache/%s/%s'

# See: https://untappd.com/api/docs
UNTAPPD_BASE_URL = 'https://api.untappd.com/v4'
UNTAPPD_CLIENT_ID = os.getenv('UNTAPPD_CLIENT_ID', None)
UNTAPPD_CLIENT_SECRET = os.getenv('UNTAPPD_CLIENT_SECRET', None)

CREDLY_BASE_URL = 'https://api.credly.com/v1.1'
CREDLY_API_KEY = os.getenv('CREDLY_API_KEY', None)
CREDLY_API_SECRET = os.getenv('CREDLY_API_SECRET', None)
CREDLY_USERNAME = os.getenv('CREDLY_USERNAME', None)
CREDLY_PASSWORD = os.getenv('CREDLY_PASSWORD', None)
CREDLY_BADGE_ID = 61615

# Mozlando values
# NUM_BEERS = 12
# START_DATETIME = datetime(2015, 12, 7)
# END_DATETIME = datetime(2015, 12, 11, 23, 59, 59, 999999)
# MOZLANDO_BEERS_AND_EARS_BADGE = 'mozlando-beers-and-ears'
# MIN_LATITUDE = 28.367444
# MAX_LATITUDE = 28.375647
# MIN_LONGITUDE = -81.553245
# MAX_LONGITUDE = -81.545134

# Test values (Cherry Street in Tulsa Nov 23-27)
# NUM_BEERS = 2
# START_DATETIME = datetime(2015, 11, 23)
# END_DATETIME = datetime(2015, 11, 27, 23, 59, 59, 999999)
# MIN_LATITUDE = 36.136844
# MAX_LATITUDE = 36.143845
# MIN_LONGITUDE = -95.97546
# MAX_LONGITUDE = -95.940098
# CREDLY_BADGE_ID = 61628

# Test values (Portland Nov 3-6)
NUM_BEERS = 2
START_DATETIME = datetime(2015, 11, 3)
END_DATETIME = datetime(2015, 11, 6, 23, 59, 59, 999999)
MIN_LATITUDE = 45.521143
MAX_LATITUDE = 45.526412
MIN_LONGITUDE = -122.684202
MAX_LONGITUDE = -122.671810
CREDLY_BADGE_ID = 61628
